#!/bin/bash
version=1.0
# Script created by Geri O. Morales, based on a script I found on stackoverblow
# (I have lost the source). For usage examples see:
# http://bluesimplex.com/2017/02/23/automatically_download_latex_bibliographies_from_mathscinet.html

BIBFILE=$2".bib"
LOGFILE=$1".log"

# Test if you have access to MathSciNet
wget -q http://www.ams.org/mathscinet/search/publications.html >> /dev/null
if [ $? -ne 0 ]; then
    echo "It seems that you don't have access to MathSciNet"
    exit
fi


mathscinet_bibtex () {
    wget \
    "http://www.ams.org/mathscinet/search/publications.html?fmt=bibtex&pg1=MR&s1=$1" \
    -q -O - | grep "<pre>" -A 1000 | sed -n -e '1,/\/pre/p' | grep -v "pre>"
    
}

array_contains () { 
    local array="$1[@]" 
    local seeking=$2
    local in=1
    for element in "${!array}"; do
        if [[ $element == $seeking ]]; then
            in=0
            break
        fi
    done
    return $in
}

echo "Retrieving bibliographies from MathScinet..."
index=0
bibcounter=0
bibitems=('empty')

for missing in $(grep -oh '\w*MR\w*' $LOGFILE); do
    if !(array_contains bibitems $missing ); then
	    mathscinet_bibtex $missing >> $BIBFILE
        #fixing bug in matscinet that sometimes deletes the first 0
        trimmedid=$(echo "$missing" | sed 's/\(MR\)0\(\w*\)\+/\1\2/')
        sed -i "s/$trimmedid/$missing/g" $BIBFILE
        echo "item ${missing} added"
        bibcounter=$((bibcounter + 1))
    fi
    bibitems[$index]=$missing
    index=$((index + 1))
done

echo "... Done! ${bibcounter} bibliography sources added to $BIBFILE"

